apiVersion: v1
kind: Service
metadata:
  name: perf-test-scraper
  labels:
    app.kubernetes.io/name: perf-test-scraper
    app.kubernetes.io/instance: perf-test-scraper
spec:
  selector:
    app: perf-test-scraper
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
