apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/name: perf-test-scraper
    app.kubernetes.io/instance: perf-test-scraper
  name: perf-test-scraper
spec:
  endpoints:
    - path: /metrics
      targetPort: 8080
      scheme: http
  selector:
    matchLabels:
      app.kubernetes.io/name: perf-test-scraper
      app.kubernetes.io/instance: perf-test-scraper